version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "1005:80"
